# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title

# Setup
title:            Open Pipetting
tagline:          'Biohacking made easy'
description:      'An organization that tries to make easy to hack bio.'
url:              http://open-pipetting.github.com/

author:
  name:           'Open Pipetting Org'

paginate:         4

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/open-pipetting/open-pipetting.github.io
